import Image from "next/image"
import { BuyButton } from "./buy-button"

const basicIncludes = ["100 recetas de paletas gourmet", "Archivos PDF listos para imprimir", "Material organizado por sabor", "Fácil de preparar en casa"]
const premiumIncludes = ["100 Recetas Organizadas", "Ingredientes y Cantidades", "Preparación Paso a Paso", "Bases Cremosas y de Frutas", "Rellenos y Combinaciones", "Sabores Económicos", "Sabores Premium", "Paletas Heladas Inspiradas en Postres", "Mini Paletas Heladas para Fiestas y Eventos", "Consejos de Textura", "Ideas de Presentación", "Acceso Digital Inmediato", "Recursos Extra"]
const bonuses = ["Recurso Extra: El Precio Justo para Cada Paleta Helada", "Recurso Extra: 12 Menús de Paletas Heladas Listos para Vender", "Recurso Extra: 50 Mensajes Listos para Vender", "Recurso Extra: 30 Combinaciones de Paletas Heladas Rentables"]

export function OfferCard({ checkoutUrl, price: _price, refPrice: _refPrice, imageSrc: _imageSrc, imageAlt: _imageAlt }: { checkoutUrl?: string; price?: string; refPrice?: string; imageSrc?: string; imageAlt?: string } = {}) {
  return <section id="oferta" className="scroll-mt-4 px-5 py-8"><div className="mx-auto flex max-w-5xl flex-col items-stretch gap-6 lg:flex-row lg:items-start"><PlanCard title="Plan Esencial" price="$3,90" refPrice="$19,90" includes={basicIncludes} checkoutUrl={checkoutUrl} buttonLabel="SÍ, QUIERO EL PLAN ESENCIAL" /><PlanCard title="Plan Completo" price="$9,90" refPrice="$39,90" includes={premiumIncludes} bonuses={bonuses} highlighted checkoutUrl={checkoutUrl} buttonLabel="SÍ, QUIERO EL PLAN COMPLETO" /></div></section>
}

function PlanCard({ title, price, refPrice, includes, bonuses, checkoutUrl, buttonLabel, highlighted = false }: { title: string; price: string; refPrice: string; includes: string[]; bonuses?: string[]; checkoutUrl?: string; buttonLabel: string; highlighted?: boolean }) {
  return <article className={`mx-auto w-full max-w-md overflow-hidden rounded-3xl bg-card shadow-xl shadow-chocolate/10 ${highlighted ? "ring-4 ring-primary/25" : ""}`}><div className={`flex items-center justify-center px-4 py-3 ${highlighted ? "bg-primary" : "bg-secondary"}`}><span className={`font-display text-sm font-extrabold uppercase tracking-wide ${highlighted ? "text-primary-foreground" : "text-primary"}`}>{highlighted ? "Mejor opción" : "Plan de entrada"}</span></div><div className="p-6"><h2 className="text-center font-display text-2xl font-extrabold text-chocolate text-balance">{title}</h2><p className="mt-1.5 text-center font-display text-base font-bold text-primary">{highlighted ? "Todo el contenido + recursos para vender" : "Lo esencial para empezar en casa"}</p><div className="mx-auto mt-4 max-w-xs overflow-hidden rounded-2xl"><Image src="/images/ebook-mockup.png" alt="Recetario digital de paletas gourmet" width={600} height={600} className="h-auto w-full object-contain" /></div><ul className="mt-4 flex flex-col gap-2">{includes.map((item) => <li key={item} className="flex items-start gap-2.5"><CheckIcon /><span className="text-sm font-medium leading-snug text-foreground">{item}</span></li>)}</ul>{bonuses ? <div className="mt-4 rounded-2xl bg-secondary p-4"><p className="mb-2 text-center font-display text-sm font-extrabold uppercase tracking-wide text-primary">Recursos extra incluidos</p><ul className="flex flex-col gap-2">{bonuses.map((item) => <li key={item} className="flex items-start gap-2.5"><GiftIcon /><span className="text-sm font-semibold leading-snug text-chocolate">{item}</span></li>)}</ul></div> : null}<div className="mt-4 text-center"><p className="text-base text-muted-foreground">Valor de referencia: <span className="font-semibold line-through">{refPrice}</span></p><p className="mt-1 font-display text-5xl font-extrabold text-primary">{price}</p><p className="mt-1 text-sm font-semibold text-pistache">Pago único · Sin mensualidades · Producto digital</p></div><div className="mt-5"><BuyButton href={checkoutUrl} subLabel="Compra 100% segura">{buttonLabel}</BuyButton></div></div></article>
}

function CheckIcon() { return <span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-pistache text-white"><svg viewBox="0 0 24 24" fill="none" className="size-3" aria-hidden="true"><path d="M20 6 9 17l-5-5" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" /></svg></span> }
function GiftIcon() { return <span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-primary text-white"><svg viewBox="0 0 24 24" fill="none" className="size-3" aria-hidden="true"><path d="M20 12v9H4v-9M2 7h20v5H2zM12 21V7M12 7S9 2 6.5 4.5 12 7 12 7zm0 0s3-5 5.5-2.5S12 7 12 7z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg></span> }
