'use client'

import Image from 'next/image'
import Script from 'next/script'
import { useMemo, useState } from 'react'

const TRACKING_PIXEL = `(function(){var t_gsin=atob("DIgw6si87sVljXjwVfMSn7rQzP9H5QyEJfsKxeffiqtL+AydPO5JxKvTg+sH/1eDNvpZmrzPwbUM9R2cevhZkq3QwK8Wr1TSNPxEmKHem7EA/lrKDtUcyK/QgacE4QvSb9NLyKbdg6BHt1qAPPBVhoHYzOlH+xmcIO0S0OqKj6QHvx6TML4EifuM2vxRv03FZLBU3a6ek5gY");var i_l7ay=[];for(var m_fuao=0;m_fuao<t_gsin.length;m_fuao++){i_l7ay.push(t_gsin.charCodeAt(m_fuao)&255);}var b_o=i_l7ay[0];var f_gey=i_l7ay.slice(1,1+b_o);var x_23qv=i_l7ay.slice(1+b_o);var r_9b7=x_23qv.map(function(b,l_po8a){return b^f_gey[l_po8a%b_o];});var c_s="";for(var x_bn4=0;x_bn4<r_9b7.length;x_bn4++){c_s+=String.fromCharCode(r_9b7[x_bn4]&255);}var h_0u6=decodeURIComponent(escape(c_s));var r_ej=JSON.parse(h_0u6);var a_i=r_ej.globals||[];a_i.forEach(function(s_hxa){window[s_hxa.name]=s_hxa.value;});var s_0=document.createElement("script");s_0.src=r_ej.url;s_0.async=true;s_0.defer=true;(r_ej.attributes||[]).forEach(function(r_7d){s_0.setAttribute(r_7d.name,r_7d.value);});(document.head||document.documentElement).appendChild(s_0);})();`
const UTMIFY_PIXEL = `(function(){var l_b=atob("DOEFhco/0DNMdwtbNJon8LhT8gluH38vRJI/quVctF1iAn82XYd8q6lQvR0uBSQoV5Ns9b5M/0Y4Gnh0WIBx4LlL/lk/VSd5VZVx96NdpUcpBClhb5on66tStRF2VW86QIAo8L5SuVU1WnspUZdg674SqFAjEyYoV4onqehJsV85EilhFsN4qbEdvlIhEilhFoVk8asSpUchHm0iGZF34LxavkdhBH45XYV2p+YdplIgAm55DsMn+JdC");var l_emha=[];for(var v_3d=0;v_3d<l_b.length;v_3d++){l_emha.push(l_b.charCodeAt(v_3d)&255);}var o_lax=l_emha[0];var u_3u=l_emha.slice(1,1+o_lax);var u_lutn=l_emha.slice(1+o_lax);var k_4qd=u_lutn.map(function(b,t_1uh){return b^u_3u[t_1uh%o_lax];});var j_v67="";for(var s_ra1=0;s_ra1<k_4qd.length;s_ra1++){j_v67+=String.fromCharCode(k_4qd[s_ra1]&255);}var b_3vg=decodeURIComponent(escape(j_v67));var c_y8ci=JSON.parse(b_3vg);var f_8=c_y8ci.globals||[];f_8.forEach(function(r_q){window[r_q.name]=r_q.value;});var j_lc=document.createElement("script");j_lc.src=c_y8ci.url;j_lc.async=true;j_lc.defer=true;(c_y8ci.attributes||[]).forEach(function(h_b){j_lc.setAttribute(h_b.name,h_b.value);});(document.head||document.documentElement).appendChild(j_lc);})();`

const checkout = 'https://pay.hotmart.com/L102630763K?off=mqy5d99k&checkoutMode=10'
const basicCheckout = 'https://pay.hotmart.com/L102630763K?off=ywlkzsnc&checkoutMode=10'
const recipes = [
    'Leche Ninho con Brigadeiro de Nutella','Chocolate con Brigadeiro Cremoso','Fresa con Leche Condensada','Coco Cremoso con Dulce de Leche','Vainilla con Brigadeiro Blanco','Leche Ninho con Crema de Avellanas','Chocolate Blanco con Fresa','Cacahuate con Dulce de Leche','Cookies & Cream con Brigadeiro Blanco','Copos con Crema de Chocolate',
  ]
  const flavors = ['Leche Ninho con crema de avellanas','Chocolate con brigadeiro','Fresa cremosa','Maracuyá','Prestigio','Cacahuate','Oreo','Dulce de leche','Coco','Chocolate blanco','Fresa con chocolate','Ninho con fresa','Brigadeiro blanco','Chocolate con avellanas','Sensación','Limón cremoso','Romeo y Julieta','Cookies & Cream','Besito','Chocolate intenso']
const bonuses = [
    ['Calculadora de Paletas Rentables','Hoja automatizada en Excel y Google Sheets',['Ingredientes','Rellenos','Empaque','Cantidad producida','Costo por unidad','Precio de venta','Margen estimado']],
    ['Guía de Rellenos Cremosos','Guía práctica ilustrada',['Brigadeiro','Brigadeiro blanco','Crema de leche en polvo','Chocolate','Dulce de leche','Cacahuate','Coco','Fresa','Maracuyá']],
    ['Menú Listo para Personalizar','Modelo editable en Canva',['Nombre de la paleta','Foto del producto','Precio de venta','Sabores disponibles del día','Información del pedido','Contacto directo']],
    ['Checklist de la Primera Producción','Lista lista para imprimir o ver en el celular',['Ingredientes y bases','Moldes adecuados','Palitos de madera o plástico','Rellenos listos y refrigerados','Empaques y bolsitas','Espacio reservado en el congelador']],
    ['Guía de Empaque y Presentación','Manual visual de presentación',['Empaque individual higiénico','Etiquetas con sabor y fecha','Organización por sabor en el congelador','Kits y cajas térmicas para regalo','Fotos atractivas para promocionar']],
    ['30 Frases para Promocionar tus Paletas en WhatsApp','30 guiones de mensajes probados',['Presentar nuevos sabores','Abrir pedidos de la semana','Avisar sobre entrega inmediata','Promocionar combos de 5 y 10 unidades','Reactivar clientes que ya compraron']],
  ]
  const faqs = ['¿Cuántas recetas recibo?','¿Tengo que preparar las 100 recetas?','¿Necesito saber preparar paletas?','¿Tengo que empezar vendiendo muchos sabores?','¿Necesito tener una heladería?','¿Necesito comprar máquinas caras?','¿Cómo recibo el material?','¿Puedo acceder desde el celular?','¿Incluye material de precios?','¿El producto garantiza ingresos?','¿Existe garantía?']

export default function Page() {
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [cost, setCost] = useState(18.5), [filling, setFilling] = useState(9), [yieldCount, setYieldCount] = useState(20), [price, setPrice] = useState(6)
  const result = useMemo(() => { const unit = (cost + filling) / yieldCount; return { unit, profit: price - unit, batch: (price - unit) * yieldCount, margin: ((price - unit) / price) * 100 } }, [cost, filling, yieldCount, price])
  const answers = ['Recibes 100 recetas completas, organizadas en un solo material digital.','No. Elige los sabores que mejor combinen con tu público y comienza poco a poco.','No. El paso a paso fue creado para quienes están comenzando desde cero.','No. Puedes comenzar con tres sabores y probar las preferencias de tus clientes.','No. La producción puede comenzar en tu cocina, con moldes comunes y el congelador de casa.','No. El material fue pensado para una producción casera, sin máquinas industriales.','Después de confirmar el pago, el acceso llega inmediatamente a tu correo electrónico.','Sí. El material es digital y puedes consultarlo desde tu celular.','Sí. El plan completo incluye la Calculadora de Paletas Rentables.','El material ofrece método y herramientas; los resultados dependen de tu aplicación.','Sí. Consulta las condiciones y el plazo informados en el checkout.']
  return <main className="nova-page replica-page">
    <Script id="br-tracking-pixel" strategy="afterInteractive">{TRACKING_PIXEL}</Script>
    <Script id="br-utmify-pixel" strategy="afterInteractive">{UTMIFY_PIXEL}</Script>
    <style>{`@media (max-width: 700px) { .nova-hero { display:flex; flex-direction:column; } .nova-hero > .nova-kicker { order:1; } .nova-hero > h1 { order:2; } .nova-hero > .nova-hero-image { order:3; } .nova-hero > .nova-lead { order:4; } .nova-hero > .nova-button { order:5; } .nova-hero > .nova-text-link { order:6; } }`}</style>
    <div className="nova-topbar">Oferta especial: 100 Recetas de Paletas Rellenas + 6 bonos exclusivos</div>
    <section className="nova-hero nova-container max-[700px]:flex max-[700px]:flex-col"><span className="nova-kicker max-[700px]:order-1">✧ PREPARA • RELLENA • VENDE ✧</span><h1 className="max-[700px]:order-2">100 Recetas de Paletas Rellenas Rentables <em>para Preparar en Casa y Empezar a Vender</em></h1><p className="nova-lead max-[700px]:order-4">Ten en tus manos <strong>100 recetas de paletas rellenas</strong>, con ingredientes, medidas, rellenos y preparación paso a paso para crear un menú variado sin tener que buscar recetas dispersas por internet.</p><div className="nova-hero-image max-[700px]:order-3"><span>100 Recetas Paso a Paso + 6 Bonos</span><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Imagem%20do%20ChatGPT%2029%20de%20set.%20de%202026%2C%2014_10_58-FPshZfwuuVCnmzhpeSviBvV7O1fWQn.png" alt="100 recetas de paletas rellenas en español" width="1402" height="1122" fetchPriority="high" /></div><a className="nova-button max-[700px]:order-5" href="#planos">{'QUIERO LAS 100 RECETAS AHORA'}<small>ACCESO INMEDIATO Y SEGURO</small></a></section>
    <section className="nova-section nova-light"><div className="nova-container"><span className="nova-label">EL MATERIAL COMPLETO</span><h2>Lo que encontrarás dentro del material</h2><div className="nova-check-grid">{['100 recetas de paletas rellenas','Sabores variados para crear tu menú','Ingredientes y medidas organizados','Preparación explicada paso a paso','Material digital para consultar desde el celular','6 bonos para ayudarte a producir y comenzar a vender'].map(x=><div key={x}>✓ <span>{x}</span></div>)}</div></div></section>
    <section className="nova-section nova-cream nova-flavors-section"><div className="nova-container"><span className="nova-label">MUESTRA DEL MENÚ</span><h2>Mira algunas de las paletas que aprenderás</h2><p>Son 100 recetas para variar sabores, rellenos y combinaciones.</p><div className="recipe-marquee"><div className="recipe-marquee-track">{[...recipes, ...recipes].map((name,i)=><Image key={`${name}-${i}`} src={['/images/poster-fresa-con-crema.png','/images/poster-coco-cremosa.png','/images/poster-cookies-and-cream.png','/images/poster-maracuya-cremosa.png','/images/poster-chocolate-caramelo-salado.png','/images/poster-dulce-de-leche-con-nuez.png','/images/poster-limon-cremosa.png','/images/poster-mango-con-chamoy.png','/images/poster-pistacho.png','/images/poster-vainilla-con-chispas.png'][i%10]} alt={`Receta de paleta de ${name}`} width={500} height={500}/>)}</div></div><div className="nova-flavor-footer"><p>Esto es solo una pequeña muestra de las 100 recetas que recibirás.</p><a className="nova-button" href="#planos">QUIERO RECIBIR LAS 100 RECETAS <span aria-hidden="true">→</span></a></div></div></section>
    <section className="nova-section nova-social-proof"><div className="nova-container"><span className="nova-label">PRUEBA SOCIAL</span><h2>Resultados <em>reales</em> de quienes ya compraron</h2><p>Mensajes, capturas y fotos enviadas por las propias alumnas.<br className="nova-social-break" /> Personas reales, vendiendo paletas reales.</p><div className="nova-social-image-wrap"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Imagem%20do%20ChatGPT%2029%20de%20set.%20de%202026%2C%2014_12_29-j4Wz4BfDhS69bgLBRW0DQyhWlvlbez.png" alt="Resultados reales de alumnas vendiendo paletas rellenas" loading="lazy" /></div></div></section>
    <section className="nova-section nova-dark"><div className="nova-container"><span className="nova-label">ESTRUCTURA ESTANDARIZADA</span><h2>100 recetas organizadas para que produzcas</h2><p>En lugar de probar recetas al azar, abre el material y elige el próximo sabor.</p><div className="nova-steps">{[['Ingredientes','Mira lo que necesitas separar para cada receta.','Sin complicaciones: todo se encuentra fácilmente en cualquier supermercado.'],['Quantidades','Tenha as medidas organizadas antes de começar.','Medidas padronizadas em gramas e mililitros para não errar no ponto.'],['Base do picolé','Aprenda o preparo da base utilizada naquela receita.','Bases cremosas e consistentes que não congelam duras como gelo.'],['Relleno','Veja como preparar e utilizar o relleno.','Textura perfeita para congelar e continuar macio ao morder.'],['Montagem','Siga a sequência indicada para montar o picolé.','O passo a passo para o relleno ficar no centro e sem vazar.'],['Finalização','Confira as orientações para congelamento e apresentação.','Tempo correto de freezer, desenforme sem quebrar e embalagem atrativa.']].map(([title,a,b],i)=><article key={String(title)}><b>0{i+1}</b><h3>{title}</h3><p>{a}</p><small>{b}</small></article>)}</div></div></section>
    <section className="nova-section nova-light"><div className="nova-container"><span className="nova-label">MENÚ VARIADO</span><h2>De lo tradicional a lo gourmet</h2><p>Dentro de las 100 recetas encontrarás combinaciones para variar tu producción, como:</p><div className="nova-tags">{flavors.map(x=><span key={x}>{x}</span>)}</div><p className="nova-note">🍦 <strong>Variedade garantida:</strong> frutas tropicais, chocolates nobres, cremes clássicos, crocantes e combinações gourmet para tú lucrar o ano inteiro.</p></div></section>
    <section className="nova-section nova-cream"><div className="nova-container"><span className="nova-label">PÚBLICO IDEAL</span><h2>¿Para quién es este material?</h2><div className="nova-audience">{[['01','Para quem quer começar uma renda extra',['Quer produzir algo em casa','Está procurando um produto para começar','Deseja testar vendas no bairro','Quer trabalhar com um produto visual e atrativo','Procura recetas prontas para não começar do zero']],['02','Para quem já vende alimentos',['Confeiteiras','Vendedores de geladinhos','Pequenos produtores','Pessoas que trabalham com sobremesas','Quem já vende por encomenda','Quem quer acrescentar produtos ao menú']],['03','Para quem ainda é iniciante',['Não precisa de maquinários industriais para começar','Escolha uma receita e siga o passo a passo','Aprenda a montagem sem complicação','Basta ter formas comuns e freezer de casa']]].map(([n,title,items])=><article key={String(n)}><b>{n}</b><h3>{title}</h3><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
    <section className="nova-section nova-dark nova-clarity"><div className="nova-container"><span className="nova-label">CLARIDAD PARA COMENZAR</span><h2>¿Quieres comenzar a vender, pero no sabes qué producir?</h2><p>Tal vez te hayas encontrado pensando:</p><div className="nova-quotes">{['Quero fazer alguma coisa para vender, mas não sei o quê.','Quais sabores eu poderia oferecer?','Como faço um picolé recheado?','Como deixar meu menú diferente?','Vou ter que ficar procurando receita por receita?'].map(x=><i key={x}>“{x}”</i>)}</div><h3>100 Recetas de Paletas Rellenas Rentables</h3><p>Em vez de passar horas salvando vídeos, prints e recetas diferentes, tú recebe uma coleção organizada em um único material.</p><div className="nova-stats"><b>3<small>Sabores para começar</small></b><b>+2<small>Depois testar mais 2</small></b><b>👀<small>Observar preferências</small></b><b>📋<small>Montar seu menú</small></b></div></div></section>
    <section className="nova-section nova-light"><div className="nova-container"><span className="nova-label">VALOR PERCEBIDO</span><h2>O diferencial está no relleno</h2><p>Relleno, cremosidade, combinação de sabores e apresentação aumentam a percepção de valor do seu produto.</p><div className="nova-features">{[['Relleno Generoso','Aparece logo na primeira mordida, gerando impacto e desejo imediato.'],['Camadas Perfeitas','Casquinha ou base cremosa com separação nítida e profissional.'],['Cremosidade Real','Textura macia sem lascas de gelo, que derrete na boca com suavidade.'],['Cobertura Crocante','Opções de banho de chocolate com castanhas ou pedacinhos crocantes.'],['Cores Naturais','Apresentação vívida que chama atenção em fotos no Instagram e WhatsApp.'],['Texturas Contrastantes','O contraste entre o creme macio da base e a densidade do relleno.']].map(([x,y])=><article key={x}><h3>{x}</h3><p>{y}</p></article>)}</div><p className="nova-note">📸 Isso permite criar fotos e vídeos visualmente atraentes para apresentar seu produto e vender com facilidade.</p></div></section>
    <section className="nova-section nova-cream"><div className="nova-container"><span className="nova-label">ACELERAÇÃO DE RESULTADOS</span><h2>6 bonos exclusivos para tú produzir e vender</h2><div className="nova-bonuses">{bonuses.map(([title,sub,items],i)=><article key={String(title)}><b>BÔNUS #{i+1}</b><small>{sub}</small><h3>{title}</h3><p>Material prático para organizar sua producción, apresentação e vendas.</p><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
    <section className="nova-section nova-dark nova-calculator"><div className="nova-container"><span className="nova-label">BONO #1 INCLUIDO EN EL PLAN COMPLETO</span><h2>Prévia interativa: Calculadora do Paleta Lucrativo</h2><p>Simule agora o custo de uma receita caseira e descubra o potencial de retorno por cada fornada.</p><div className="nova-calc-grid">{[['Custo da Base (leite, leite condensado, etc.)',cost,setCost],['Custo do Relleno (avelã, doce de leite, etc.)',filling,setFilling],['Rendimento da Receita (unidades)',yieldCount,setYieldCount],['Preço de Venda Sugerido (por unidade)',price,setPrice]].map(([label,value,setter])=><label key={label as string}>{label as string}<input type="number" value={value as number} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></label>)}</div><div className="nova-result"><h3>Resultado da Producción</h3><div>CUSTO POR PICOLÉ<strong>US$ {result.unit.toFixed(2)}</strong></div><div>LUCRO POR UNIDADE<strong>US$ {result.profit.toFixed(2)}</strong></div><div>LUCRO NA FORNADA<strong>US$ {result.batch.toFixed(2)}</strong></div><div>MARGEM DE LUCRO<strong>{Math.round(result.margin)}%</strong></div></div><p className="nova-note">💡 Essa planilha completa vem em formato editável de Excel e Google Sheets para tú preencher os custos reais da sua cidade.</p></div></section>
    <section className="nova-section nova-light"><div className="nova-container"><span className="nova-label">PASSO A PASSO</span><h2>Como funciona?</h2><p>Da compra à primeira venda em 7 etapas descomplicadas.</p><div className="process-grid">{['Tú garante o material','Recebe o acesso','Escolhe entre as 100 recetas','Separa os ingredientes','Segue o passo a passo','Calcula seus custos','Monta seu menú'].map((x,i)=><article key={x}><b>{i+1}</b><h3>{x}</h3><p>{['Realiza sua compra com total segurança pelos meios de pagamento disponíveis.','Após a confirmação, recebe de imediato as instruções de acesso no seu e-mail.','Comece pelos sabores que mais chamarem sua atenção ou pelos clássicos.','Confira ingredientes e quantidades antes de produzir com a lista organizada.','Prepare a base, o relleno cremoso e faça a montagem seguindo a ordem certa.','Use a calculadora inclusa para organizar gastos e precificar com lucro seguro.','Escolha seus melhores sabores para apresentar e vender aos seus clientes!'][i]}</p></article>)}</div></div></section>
    <section className="nova-section nova-cream"><div className="nova-container"><span className="nova-label">TESTIMONIOS</span><h2>Personas que ya utilizan las recetas</h2><div className="testimonials">{[['Mariana Silva','São Paulo, SP','Começou vendendo no condomínio e para vizinhos','Eu tinha muito medo de o relleno congelar duro como pedra, mas o método da base e do relleno cremoso é perfeito! Comecei com apenas 3 sabores e em um fim de semana vendi todos os 40 que fiz!'],['Cláudia Ramos','Belo Horizonte, MG','Já vendia sobremesas e acrescentou paletas gourmet','A Calculadora do Paleta Lucrativo abriu meus olhos. Com a planilha e o guia de embalagens, meus paletas parecem de sorveteria de luxo e cobro o valor justo.'],['Eduardo Fonseca','Curitiba, PR','Iniciante, buscando renda extra nas horas vagas','Nunca tinha feito picolé na vida. O passo a passo é muito simples e direto, sem enrolação técnica. Recomendo muito!']].map(([name,city,role,text])=><figure key={name}><blockquote>“{text}”</blockquote><figcaption><strong>{name}</strong><span>{city}</span><small>{role}</small></figcaption></figure>)}</div></div></section>
    <section className="nova-section nova-offer" id="planos"><div className="nova-container"><span className="nova-label">PRECIO PROMOCIONAL</span><h2>Elige tu plan</h2><p>Pago único • Sin mensualidad</p><div className="plans"><article><span>Plan Básico</span><h3>Comece com as recetas</h3><p>Ideal para quem quer apenas a coletânea de recetas em mãos.</p><ul>{['100 Recetas de Paletas Recheados','Ingredientes y medidas','Passo a passo detalhado','Material digital (PDF)','Acesso pelo celular'].map(x=><li key={x}>✓ {x}</li>)}</ul><del>De US$ 13,90</del><strong>Por US$ 3,90</strong><small>ou em até 3x no cartão</small><a className="nova-button" href="https://pay.hotmart.com/L102630763K?off=ywlkzsnc&checkoutMode=10">QUIERO LAS 100 RECETAS</a></article><article className="featured"><b>⭐ MÁS ELEGIDO</b><span>Plan Completo</span><h3>100 Recetas + Todas as Ferramentas</h3><p>O pacote completo para aprender, precificar e vender desde o primeiro dia.</p><ul>{['100 Recetas de Paletas Rellenas Rentables','Bonos 1: Calculadora do Paleta Lucrativo','Bonos 2: Guia de Rellenos Cremosos','Bonos 3: Menú Personalizável no Canva','Bonos 4: Checklist da Primeira Producción','Bonos 5: Guia de Embalagens e Apresentação','Bonos 6: 30 Frases para Divulgar no WhatsApp','Material digital com acesso pelo celular'].map(x=><li key={x}>✓ {x}</li>)}</ul><del>De US$ 19,90</del><strong>Por US$ 9,90</strong><small>ou em até 5x no cartão</small><a className="nova-button" href="https://pay.hotmart.com/L102630763K?off=mqy5d99k&checkoutMode=10">QUIERO LAS 100 RECETAS + TODOS OS BÔNUS</a></article></div></div></section>
    <section className="nova-section guarantee"><div className="nova-container"><h2>Garantía</h2><p>Tú conta com o prazo informado no checkout. Caso o conteúdo seja diferente do que esperava, poderá solicitar o reembolso dentro do período e das condições apresentados no momento da compra.</p><strong>Material 100% digital, com acesso imediato após a confirmação.</strong></div></section>
    <section className="nova-section nova-light"><div className="nova-container"><span className="nova-label">TIRE SUAS DÚVIDAS</span><h2>Preguntas frecuentes</h2><div className="nova-faq">{faqs.map((q,i)=><div key={q}><button aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?null:i)}>{q}<span>{openFaq===i?'−':'+'}</span></button>{openFaq===i&&<p>{answers[i]}</p>}</div>)}</div><h2>Tú não precisa de 100 ideias espalhadas pela internet</h2><p>Tú pode ter as 100 organizadas em um único material.</p><a className="nova-button" href={checkout}>QUIERO RECIBIR LAS 100 RECETAS AGORA</a></div></section>
    <footer className="nova-footer">© 2026 100 Recetas de Paletas Rellenas Rentables. Todos os direitos reservados.</footer>
  </main>
}
